#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
    shift
fi

cd ${plugin.symbolic.name}.targetplatform
./plugin-builder $DEBUG_MODE ../${plugin.symbolic.name} ../${plugin.symbolic.name}.test
