#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd com.ingeint.requisitions.targetplatform
./plugin-builder $DEBUG_MODE ../com.ingeint.requisitions ../com.ingeint.requisitions.test
