#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=-X
    shift
fi

javac TargetPlatformPomGenerator.java
java TargetPlatformPomGenerator "$@"
mvn verify -Didempiere.target=com.ingeint.template.p2.targetplatform $DEBUG_MODE
javac TargetPlatformPluginTagger.java
java TargetPlatformPluginTagger "$@"