#!/usr/bin/env sh

set -e

OPTIONS=

for arg in "$@"
do
  if [ "$arg" = "debug" ]; then
      OPTIONS="$OPTIONS -X"
      echo "Debug mode"
      shift
  fi

  if [ "$arg" = "commit" ]; then
      echo "Using commit qualifier"
      [ -z "$GIT_COMMIT" ] && echo "Set GIT_COMMIT variable first" && exit 1
      OPTIONS="$OPTIONS -DforceContextQualifier=$GIT_COMMIT"
      shift
  fi

  if [ "$arg" = "build" ]; then
      echo "Using build number qualifier"
      [ -z "$BUILD_NUMBER" ] && echo "Set BUILD_NUMBER variable first" && exit 1
      OPTIONS="$OPTIONS -DforceContextQualifier=$BUILD_NUMBER"
      shift
  fi
done

javac TargetPlatformPomGenerator.java
java TargetPlatformPomGenerator "$@"
mvn validate -Didempiere.target=com.ingeint.template.p2.targetplatform $OPTIONS
mvn verify -Didempiere.target=com.ingeint.template.p2.targetplatform $OPTIONS
javac TargetPlatformPluginTagger.java
java TargetPlatformPluginTagger "$@"
